FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app_k8s.py .
COPY model.joblib .
EXPOSE 8000
CMD ["python", "-m", "uvicorn", "app_k8s:app", "--host", "0.0.0.0", "--port", "8000"]
